### ISSUE TITLE
Test float with approx instead of ==

### ISSUE THREAD

**Issue by ehodille** [RemDelaporteMathurin/FESTIM#496]
While running the tests on a cluster, a test failed when two floating point numbers were compared. 
The precision of the machine on which the tests were run is high, thus the precision of the number was too  high for == to be true.
A suggestion could be to replace 
``` assert a == b``` 
by 
```assert a == approx(b)```

A screenshot of the test failure is attached bellow
![image](https://user-images.githubusercontent.com/61870193/178233449-d1d79bf8-cc86-49d5-9244-b24d00fe0f21.png)

**Comment by jhdark** [comment]
This error seems to have been fixed and pushed but not sure which PR @RemDelaporteMathurin

**Comment by RemDelaporteMathurin** [comment]
Not sure this is fixed but hard to reproduce cause it's dependent on machine precision. @ehodille was running it on the cluster here

Pretty sure we still have some float comparisons here and there in the tests

**Comment by RemDelaporteMathurin** [comment]
I just checked and you're right it seems it has been fixed
https://github.com/search?q=repo%3ARemDelaporteMathurin%2FFESTIM+path%3A%2F%5Etest%5C%2F%2F+%3D%3D&type=code&p=1

Thanks!
