### ISSUE TITLE
CI with conda install

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [RemDelaporteMathurin/FESTIM#547]
Currently our CI only test FESTIM in the Docker environment.
We need to (also?) run the CI in a conda environment!

**Comment by shimwell** [comment]
in the conda meta file one can specify tests like pytest ...

https://github.com/fusion-energy/paramak/blob/6a6387ac8fcc14463820c0f18cb870c60325860a/conda/meta.yaml#L29-L45

I did not know you had a conda install for this package, is it on conda-forge or your own channel?

**Comment by RemDelaporteMathurin** [comment]
No sorry for not being clear.

FESTIM's main dependency (FEniCS) can be installed with Docker or Conda.
I'd like to test FESTIM in both environments (Docker container and conda)
