### ISSUE TITLE
Single output file for `TXTExport`

### ISSUE THREAD

**Issue by KulaginVladimir** [RemDelaporteMathurin/FESTIM#623]
For long-term transient simulations with a small timestep, FESTIM produces a lot of files, when data is exported with `TXTExport`. Won't it be more practical to have one output file? 

Possibly, smt like that can be usefull?
```python
def is_it_first_time_to_export(self, current_time, nb_iteration):
    if self.times is None:
        return True if nb_iteration == 0 else False
    else:
        return True if np.isclose(self.times[0], current_time) else False
def write(self, current_time, nb_iteration, steady):
    # create a DG1 functionspace
    V_DG1 = f.FunctionSpace(self.function.function_space().mesh(), "DG", 1)
    solution = f.project(self.function, V_DG1)
    if self.is_it_time_to_export(current_time):
        if steady:
            filename = "{}/{}_steady.txt".format(self.folder, self.label)
            header = 'x,t=steady'
        else:
            filename = "{}/{}_transient.txt".format(self.folder, self.label)
            header = 'x,t={}s'.format(current_time)
        x = f.interpolate(f.Expression("x[0]", degree=1), V_DG1)
        # if the directory doesn't exist
        # create it
        dirname = os.path.dirname(filename)
        if not os.path.exists(dirname):
            os.makedirs(dirname, exist_ok=True)
        # if steady or it is the first time to export
        # write data
        # else append new column to the existing file    
        if steady or self.is_it_first_time_to_export(current_time, nb_iteration):
            np.savetxt(filename, np.transpose([x.vector()[:], solution.vector()[:]]), header = header, delimiter = ',', comments='')
        else:
            # Update the header
            old_file = open(filename)
            header = old_file.readline().split('\n')[0] + ',t={}s'.format(current_time)
            old_file.close()
            # Append new column
            np.savetxt(filename, np.column_stack([np.loadtxt(filename, delimiter = ',', skiprows = 1), np.transpose(solution.vector()[:])]), header=header, delimiter = ',', comments='')
```

**Comment by RemDelaporteMathurin** [comment]
Hi @KulaginVladimir 

I must admit I'm not a big user of TXT exports, I usually write data to XDMF and then visualise it in Paraview. Have you ever used them?

Another alternative would be to only export the TXT at certain timesteps.

Also, for other exports (`XDMFExport`, `DerivedQuantities`) we have the option to say "write this export every N iterations". I don't remember if we have this for TXTExport or not, but that's surely something worth adding!

So in this new TXT export, instead of having 2 columns you would have multiple columns for each timestep, correct?

I think this could work!

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin, 
> Have you ever used XDMFExport ?

Yes, `XDMFExport` works fine, but I've only started using Paraview. **Related question:** is it possible to visualise XDMF directly with python?

> Also, for other exports (XDMFExport, DerivedQuantities) we have the option to say "write this export every N iterations

I suppose, `TXTExport` has `times=[..]` instead

> So in this new TXT export, instead of having 2 columns you would have multiple columns for each timestep, correct?

Yeap. Additionally, the header is written to the file. It allows having labeled columns, if one analyses the exported data with pandas/numpy.

**Comment by RemDelaporteMathurin** [comment]
> is it possible to visualise XDMF directly with python?

Yes but it's sometimes a bit finicky. I wouldn't recommend it. See [this example](https://github.com/RemDelaporteMathurin/FESTIM-workshop/blob/main/tasks/task7.ipynb).
Instead, what I usually do is export everything to XDMF then from Paraview, extract the data to csv using `Plot over line` and the `Save data` option.



> I suppose, `TXTExport` has `times=[..]` instead

You can set the export times in `TXTExport` and then add [milestones](https://github.com/RemDelaporteMathurin/FESTIM/pull/568) to the simulation.




> Yeap. Additionally, the header is written to the file. It allows having labeled columns, if one analyses the exported data with pandas/numpy.

This sounds very good to me! Feel free to [open a PR](https://festim.readthedocs.io/en/latest/devguide/index.html) 🚀
